services:
 
  node1:
    image: dolthub/dolt:latest
    container_name: node1
    hostname: node1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - node1_data:/root/dolt
      - ./init.sh:/init.sh
      - ./creds:/root/creds
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

  node2:
    image: dolthub/dolt:latest
    container_name: node2
    hostname: node2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - node2_data:/root/dolt
      - ./init.sh:/init.sh
      - ./creds:/root/creds
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

  node3:
    image: dolthub/dolt:latest
    container_name: node3
    hostname: node3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - node3_data:/root/dolt
      - ./init.sh:/init.sh
      - ./creds:/root/creds
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

volumes:
  node1_data:
  node2_data:
  node3_data:
  doltlab_pg_data:

networks:
  doltlab:
    external: true