services:
  local-node:
    image: dolthub/dolt
    container_name: local-node
    hostname: local-node
    environment:
      - DOLT_ROOT_PASSWORD=password
      - DOLT_ROOT_HOST=%
    volumes:
      - localnode_data:/root/dolt
      - dolt_remote_data:/dolt-remote
      - ./remote/remote_init.sh:/init.sh
      - ./remote/db_init.sql:/db_init.sql
    ports:
      - "3307:3306"
    entrypoint: >
      sh /init.sh

  dolt-workbench:
    image: dolthub/dolt-workbench:latest
    container_name: dolt-workbench
    hostname: dolt-workbench
    depends_on:
      local-node:
        condition: service_started
    ports:
      - 3000:3000
      - 9002:9002
    volumes:
      - ./workbench_store:/app/graphql-server/store
      - dolt_remote_data:/dolt-remote

  node1:
    image: dolthub/dolt
    container_name: node1
    hostname: node1
    depends_on:
      - local-node
    ports:
      - "3309:3306"
    environment:
      - DOLT_ROOT_PASSWORD=password
      - DOLT_ROOT_HOST=%
    volumes:
      - node1_data:/root/dolt
      - dolt_remote_data:/dolt-remote
      - ./nodes/init.sh:/init.sh
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

  node2:
    image: dolthub/dolt
    container_name: node2
    hostname: node2
    depends_on:
      - local-node
    ports:
      - "3310:3306"
    environment:
      - DOLT_ROOT_PASSWORD=password
      - DOLT_ROOT_HOST=%
    volumes:
      - node2_data:/root/dolt
      - dolt_remote_data:/dolt-remote
      - ./nodes/init.sh:/init.sh
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

  cold-node:
    image: dolthub/dolt
    container_name: cold-node
    hostname: cold-node
    depends_on:
      - local-node
    ports:
      - "3311:3306"
    environment:
      - DOLT_ROOT_PASSWORD=password
      - DOLT_ROOT_HOST=%
    volumes:
      - node3_data:/root/dolt
      - dolt_remote_data:/dolt-remote
      - ./nodes/cold_node.sh:/init.sh
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"



volumes:
  localnode_data:
  node1_data:
  node2_data:
  node3_data:
  dolt_remote_data:
