services:
  dolt-remote:
    image: dolthub/dolt-sql-server
    container_name: dolt-remote
    hostname: dolt-remote
    environment:
      - DOLT_ROOT_PASSWORD=password
      - DOLT_ROOT_HOST=%
    volumes:
      - dolt_remote_data:/dolt-remote
      - ./remote_init.sh:/init.sh
    ports:
      - "3307:3306"
    entrypoint: >
      sh /init.sh

  dolt-workbench:
    image: dolthub/dolt-workbench
    container_name: dolt-workbench
    hostname: dolt-workbench
    depends_on:
      - dolt-remote
    ports:
      - 3000:3000
      - 9002:9002
    environment:
      - DW_DB_CONNECTION_URI=mysql://root:password@dolt-remote:3306/test-repo
    volumes:
      - ./workbench-store:/app/graphql-server/store
      - dolt_remote_data:/dolt-remote

  node1:
    image: dolthub/dolt
    container_name: node1
    hostname: node1
    depends_on:
      - dolt-remote
    volumes:
      - node1_data:/root/dolt
      - dolt_remote_data:/dolt-remote
      - ./node1/init.sh:/init.sh
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

  node2:
    image: dolthub/dolt
    container_name: node2
    hostname: node2
    depends_on:
      - dolt-remote
    volumes:
      - node2_data:/root/dolt
      - dolt_remote_data:/dolt-remote
      - ./nodeX/init.sh:/init.sh
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

  node3:
    image: dolthub/dolt
    container_name: node3
    hostname: node3
    depends_on:
      - dolt-remote
    volumes:
      - node3_data:/root/dolt
      - dolt_remote_data:/dolt-remote
      - ./nodeX/init.sh:/init.sh
    working_dir: /root/dolt
    entrypoint: sh -c ". /init.sh && tail -f /dev/null"

volumes:
  node1_data:
  node2_data:
  node3_data:
  dolt_remote_data:
